### ISSUE TITLE
Conformal Prediction V1.1 tasks

### ISSUE THREAD

**Issue by noxan** [ourownstory/neural_prophet#1017]
Issue to track the follow up tasks from https://github.com/ourownstory/neural_prophet/pull/802/

- [X] There is quite a lot of code which is currently disabled as comments, we should either finish the implementation or remove the unused comments ([ref](https://github.com/ourownstory/neural_prophet/pull/802#discussion_r1037701222))
- [x] There seems to be an open todo with auto regression enabled and assertion of n_train >= 1 ([ref](https://github.com/ourownstory/neural_prophet/pull/802#discussion_r1037700769))
- [x] The `conformalize_predict` method is currently only commented, do we finish this or remove it again? ([ref](https://github.com/ourownstory/neural_prophet/pull/802/files/fde920ee22a08ed912870843e03e9563a1c0cd0e#r1037699461))

**Comment by Kevin-Chen0** [comment]
Additional tasks:

[] -

**Comment by noxan** [comment]
I believe closing this issue was not intentional

**Comment by Kevin-Chen0** [comment]
Moved the following tasks Conformal Prediction V1.2 https://github.com/ourownstory/neural_prophet/issues/1101:
- Documentation We currently have three ways to work with uncertainty (QR, CP, and CQR): for me it's not really clear when to use which and why? Could either be addressed in some tutorial or if the API would be more similar I might get a better idea of what is the difference and how I switch between them. ([ref](https://github.com/ourownstory/neural_prophet/pull/802#discussion_r1032853973))
- Create conformal prediction method `auto`, which automatically selects "best" conformal prediction method based on the NP params (e.g. quantiles included or not).
- Add `.conformal_test()` method in forecaster.py to wrap around the `.test()`, just like `.conformal_predict()` with `.predict()`.
- Add Continuous Ranked Probability Score (CRPS) as a metric for probabilistic forecast. [Source](https://datumorphism.leima.is/cards/time-series/crps/)
