### ISSUE TITLE
Conformal Prediction V1.2 tasks

### ISSUE THREAD

**Issue by Kevin-Chen0** [ourownstory/neural_prophet#1101]
Issue to track the follow up tasks from Conformal Prediction V1.1 #1017 and additions:
- [ ] Make documentation and tutorial about the different methods of uncertainty (i.e., QR, CP, and CQR). Compare their differences, explain when to use which and why, and how to switch between them if necessary. ([ref](https://github.com/ourownstory/neural_prophet/pull/802#discussion_r1032853973))
- [ ] Move `interval_width` and `miscoverage_rate` conformal evaluation performance metrics inside of `Conformal` class.
- [ ] Enable asymmetrical or adaptive CP intervals for CQR. Whitepaper [source](https://arxiv.org/abs/1905.03222).
- [ ] Simplify/standardize uncertainty column name to always be `f"yhat{step_number} {quantile}%"` for all QR, CP, CQR outputs. (instead of  e.g. `f"yhat{step_number} {quantile}% - qhat{step_number}"`, possibly add a separate column or a separate return value for qhat).
- [ ] Make CP compatible with all applicable plotting functions, including  `plot_latest_forecast()` and `plot_components()`.

**Comment by Kevin-Chen0** [comment]
Moved some of the tasks to CP v1.3 or Issue #1151.
