### ISSUE TITLE
Refactor forecaster.py

### ISSUE THREAD

**Issue by ourownstory** [ourownstory/neural_prophet#1133]
- [x] Create an overview of all functions to be moved (incl origin, destiny and their places of use)
- [x] Simplify the file, move functions to util functions
- [x] No private functions in forecaster.py -> move to to other appropriate files
- [ ] Restructure utils files (coherence, move more into appropriate separate files, maybe rename utils to something without ‘util’)
