### ISSUE TITLE
Uncertainty V1.0

### ISSUE THREAD

**Issue by Kevin-Chen0** [ourownstory/neural_prophet#1151]
This is a meta-tracker for all the uncertainty tasks for NeuralProphet v1.0, including both for **Quantile Regression (QR)** and **Conformal Prediction (CP)**.

## Architecture
- [x] #1213 
- [x]  #1214 

## Quantile Regression
- [ ] #1102 

## Conformal Prediction
- [x] #1209
- [x] #1189
- [ ] Add `.conformal_test()` method in forecaster.py to wrap around the `.test()`, just like `.conformal_predict()` with `.predict()`.
- [ ] Create conformal prediction method `auto`, which automatically selects "best" conformal prediction method based on the NP params (e.g. quantiles included or not).
- [ ] Add Continuous Ranked Probability Score (CRPS) as a metric for probabilistic forecast. [Source](https://datumorphism.leima.is/cards/time-series/crps/)
- [ ] Add Conformal Predictive Distributions (CPDs) as an uncertainty quantification (UQ) type instead of only prediction intervals (PIs).
- [ ] Support an arbitrary number of quantiles (1,2,3,4,5,..) instead of only 2.

## Plotting
- [ ]  enable `plot_latest_forecast()` on conformalized `forecast` dataset

Future Work:
- Modular Conformal Calibration. [Source](https://arxiv.org/abs/2206.11468)

**Comment by leoniewgnr** [comment]
PR will be closed for V2 release, but ideas and feature request are saved and might be realized in V2.
